name: HurtHealth
version: 1.1b
main: com.playernguyen.HurtHealth
depend: [HolographicDisplays]
author: [Player_Nguyen]
commands:
    hurthealth:
        usage: /hurthealth <subcommand>
permissions:
    hurthealth.help:
        default: op
    hurthealth.*:
        default: op
        children:
            hurthealth.reload: true
            hurthealth.info: true
            hurthealth.help: true
            hurthealth.cmd: true
    hurthealth.reload:
        default: op
    hurthealth.info:
        default: op
    hurthealth.cmd:
        default: op